Packer base
Otus-DevOps-2021-05/ASobakin_infra pull request #4
Opened 2021-08-13 10:01 UTC by ASobakin

Изучены параметры Packer Создан файл variables.json.examples с вымышленными значениями.Файл с реальными добавлен к .gitignore.

2021-08-16 10:28 UTC, mrgreyves requested changes
Здравствуйте!) Проверил ваше дз. К сожалению не хватает достаточно большого количества файлов. Рекомендую снова свериться с методичкой. ДЗ возвращаю на доработку =)

2021-08-16 12:58 UTC, ASobakin commented
Вроде по основному все было. добавил доп дз. или все ровно что то упускаю?

2021-08-16 15:06 UTC, mrgreyves requested changes
Здравствуйте!) Failed to parse template: Error parsing JSON: invalid character ']' looking for beginning of value 29 строка, выглядит как почти что все готово =)

2021-08-17 05:21 UTC, ASobakin commented
да, дейсвтительно. поправил

2021-08-17 08:29 UTC, mrgreyves approved these changes
Здравствуйте!) Вот теперь апрув!)

2021-08-17 08:31 UTC, merged