HW8
Otus-DevOps-2021-05/ASobakin_infra pull request #5
Opened 2021-08-18 14:25 UTC by ASobakin

Изучены параметры Terraform Описана инфраструктура при помощи terraform и провайдера yandex. Выложен файл terraform.tfvars.example

2021-08-20 10:31 UTC, mrgreyves requested changes
Здравствуйте!) Проверил ваше дз. Стоит свериться с методичкой, не хватает некоторых файлов. ДЗ возвращаю на доработку =)

2021-08-30 18:34 UTC, ASobakin commented
Добавил lb.tf из задания со звездочкой, я вроде в ридми сразу не заявлял что его сделаю, если не хватает чего то еще, можете направить, а то я не понимаю. Спасибо!

2021-08-31 17:17 UTC, mrgreyves requested changes
Здравствуйте!)
Балансировщик это дополнительное задание и учитывается оно отдельно
Тут вопрос немного в другом
Если быть уж совсем точным то в ×  Directory terraform/files should exist

2021-08-31 17:24 UTC, ASobakin commented
согласен, не прав, положил туда puma.service и deploy.sh

2021-08-31 17:25 UTC, mrgreyves commented
Тогда пока что двигать карточку не буду, пофиксите и перезапустите тесты =)

2021-08-31 17:32 UTC, ASobakin commented
так вроде все

2021-09-02 09:58 UTC, mrgreyves commented
И последняя правка
File .gitignore content should match /\n\Z/
Добавьте пустую строку =)

2021-09-02 10:01 UTC, ASobakin commented
а я голову ломал, что такое)
готова

2021-09-02 10:03 UTC, mrgreyves commented
Штош, бывает и такое =)

2021-09-02 10:03 UTC, mrgreyves approved these changes
Апрув!)

2021-09-02 10:20 UTC, merged